### ISSUE TITLE
Create Toggle Button for Viewing Direction

### ISSUE THREAD

**Issue by schwemmer** [bodleian/iiif-manifest-editor#18]
Should this go into the Sequence panel? 
Should toggling this option update the viewingDirection property in the manifest (most likely yes)?

**Comment by emmastanford** [comment]
I asked a couple of people where they would expect to find this, and they said the thumbnail panel first, but the sequence panel was their second guess. So that would be reasonable, if you don't think there's a good place to put it in or near the thumbnail panel. Would it be possible to add an option to the canvas action menu called "Change viewing direction", which opens up the sequence metadata panel when you click on it?

I agree that toggling should change the viewingDirection property in the manifest.
