### ISSUE TITLE
Python server

### ISSUE THREAD

**Issue by ahankinson** [bodleian/iiif-manifest-editor#32]
I would like to add a small Python server to this project, since it will fit in better with our deployments at the Bodleian. 

Is the purpose of the Express `server.js` just to serve out the `public` directory? Is there anything else I should keep in mind when creating this?

**Comment by cubap** [comment]
Express also runs the manifest uploader, but that should be easy to port. See the end of server.js.

**Comment by schwemmer** [comment]
@ahankinson Sorry for the late reply, just returned from vacation. @cubap is correct: Express is currently only used to handle manifest uploads. If you wanted to add a Python server I think it should better be in a fork since we intentionally limited the tech stack to Node. But I see that you have closed the PR anyway.
