### ISSUE TITLE
More robust response to invalid manifests

### ISSUE THREAD

**Issue by emmastanford** [bodleian/iiif-manifest-editor#35]
If you try to load or import canvases from an invalid manifest, you won't be able to load a valid manifest either until you clear your browser cache. It would be good if the editor were a bit more resilient in these cases.

To reproduce this error:
1. Go to iiif.bodleian.ox.ac.uk/manifest-editor/.
2. Choose "New manifest".
3. Go to "Import canvases".
4. Load this manifest: http://www.qdl.qa/en/iiif/81055/vdc_100000000241.0x0003bd/manifest
5. After closing the error message, try to load this manifest: http://iiif.bodleian.ox.ac.uk/iiif/manifest/beeedb51-90cd-4119-84fb-c7e9ffb0b214.json. You should see the same error message.
6. Try again after clearing the browser cache.

**Comment by schwemmer** [comment]
Several issues to consider:

- as far as I know, in general, if there is a JavaScript error, React apps don't recover and have to be restarted. The only way around this for now seems to be to put try/catch blocks around every single render method 

- one of the issues here is that we store successfully loaded manifests to local storage when importing canvases. If they generate a JavaScript error, they will continue to do so because they are loaded from local storage until cache / local storage is cleared. This, of course, is problematic. However, it is difficult to test run each manifest against all components before storing it in local storage

- we could validate each manifest before loading it. Drawbacks to this approach would be a) performance and b) you could no longer edit invalid manifests to make them valid

- even if a manifest is valid, it might still generate JavaScript errors because the app doesn't support the type of data it contains, so validation is no guarantee that a manifest will work in the editor.

- While the Qatar manifest referenced in point 4 above doesn't validate, it does seem to be valid (might be a bug in the IIIF Presentation Validator) and it does load in Mirador

- for now, the approach I took is to figure out the problem with this particular manifest and fix it. The problem here was multilingual/localized canvas labels

- the Oxford manifest referenced in point 5 above currently doesn't work at all. That's a separate issue though.

The fix for localized canvas values is in branch bugfix/issue-35 and needs some more testing before it can be merged to master.

**Comment by schwemmer** [comment]
@emmastanford The fix for the Qatar manifest has been merged to master, so this manifest:  http://www.qdl.qa/en/iiif/81055/vdc_100000000241.0x0003bd/manifest should work now.

**Comment by emmastanford** [comment]
That's great!
